require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  EnabledByDefault: true

# Disabled because it would mark a lot of offenses unnecessarily.
Lint/ConstantResolution:
  Enabled: false

# Copyright is not necessary for each file.
Style/Copyright:
  Enabled: false

# Agree with some of them individually, but as a whole, it don't behave the way I want it to, so set it to Disable.
Style/MethodCallWithArgsParentheses:
  Enabled: false
