[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    let g:airline#extensions#ale#enabled = 1
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let NERDTreeShowHidden = 1

    nnoremap <Space>T :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
    nnoremap <Space>n :LspNextError<CR>
    nnoremap <Space>p :LspPreviousError<CR>
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''!has('nvim')'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim')'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
hook_add = '''
    let g:extra_whitespace_ignored_filetypes = ['unite']
    autocmd BufWritePre * :FixWhitespace
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'raghur/vim-ghost'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
nmap <Space>f [find]
nnoremap [find]f :<C-u>Unite file<CR>
nnoremap [find]b :<C-u>Unite buffer<CR>
nnoremap [find]t :<C-u>Unite tab<CR>
nnoremap [find]m :<C-u>Unite file_mru<CR>
nnoremap [find]a :<C-u>Unite file_rec<CR>
nnoremap [find]l :<C-u>Unite line<CR>
nnoremap [find]w :<C-u>Unite grep:.<CR><C-R><C-W><CR>
'''

[[plugins]]
repo = 'basyura/unite-rails'
hook_add = '''
nmap <Space>r [rails]
nnoremap [rails]m :<C-u>Unite rails/model<CR>
nnoremap [rails]v :<C-u>Unite rails/view<CR>
nnoremap [rails]c :<C-u>Unite rails/controller<CR>
nnoremap [rails]h :<C-u>Unite rails/helper<CR>
nnoremap [rails]g :<C-u>Unite rails/gemfile<CR>
nnoremap [rails]s :<C-u>Unite rails/stylesheet<CR>
nnoremap [rails]j :<C-u>Unite rails/javascript<CR>
nnoremap [rails]l :<C-u>Unite rails/log<CR>
'''

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
nmap <Space>g [git]
nnoremap [git]a :<C-u>Git write<CR>
nnoremap [git]c :<C-u>Git commit<CR>
nnoremap [git]d :<C-u>Git diff<CR>
nnoremap [git]b :<C-u>Git blame<CR>
nnoremap [git]m :<C-u>Git move<Space>
nnoremap [git]r :<C-u>Git read<CR>
nnoremap [git]s :<C-u>Git status<CR>
nnoremap [git]l :<C-u>Git log<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
